# Generated by Django 4.1.12 on 2023-12-21 09:08

from django.db import migrations, models
import tnk_quest.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Hunters',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_name', models.CharField(max_length=100)),
                ('password', tnk_quest.models.EncryptedField(max_length=1000)),
                ('portfolio', models.IntegerField(default=10000)),
            ],
        ),
        migrations.CreateModel(
            name='Quests',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('deadline', models.DateTimeField(blank=True, null=True)),
                ('rank', models.CharField(max_length=10)),
                ('overview', models.CharField(max_length=1000)),
            ],
        ),
    ]
