# Generated by Django 4.1.12 on 2023-12-22 19:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tnk_quest', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hunters',
            name='user_name',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
