# Generated by Django 4.1.12 on 2023-12-22 20:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tnk_quest', '0002_alter_hunters_user_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='quests',
            name='client',
            field=models.CharField(default='unknown', max_length=100),
        ),
    ]
