# Generated by Django 4.1.12 on 2023-12-22 21:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tnk_quest', '0003_quests_client'),
    ]

    operations = [
        migrations.AddField(
            model_name='quests',
            name='Capacity',
            field=models.IntegerField(default=10),
        ),
    ]
