# Generated by Django 4.1.12 on 2023-12-22 23:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tnk_quest', '0004_quests_capacity'),
    ]

    operations = [
        migrations.RenameField(
            model_name='quests',
            old_name='Capacity',
            new_name='capacity',
        ),
    ]
