# Generated by Django 4.1.12 on 2023-12-23 00:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tnk_quest', '0005_rename_capacity_quests_capacity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quests',
            name='title',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
