# Generated by Django 4.1.12 on 2023-12-24 03:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tnk_quest', '0006_alter_quests_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='quests',
            name='hunters',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='hunters',
            name='portfolio',
            field=models.IntegerField(default=2000),
        ),
        migrations.AlterField(
            model_name='quests',
            name='overview',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='quests',
            name='rank',
            field=models.CharField(default='C', max_length=10),
        ),
    ]
