# Generated by Django 4.1.12 on 2023-12-27 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tnk_quest', '0007_quests_hunters_alter_hunters_portfolio_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quests',
            name='hunters',
            field=models.CharField(default='', max_length=1000),
        ),
    ]
