# Generated by Django 4.1.12 on 2023-12-27 12:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tnk_quest', '0008_alter_quests_hunters'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hunters',
            name='portfolio',
            field=models.IntegerField(default=1),
        ),
    ]
