# Generated by Django 4.1.12 on 2023-12-27 15:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tnk_quest', '0009_alter_hunters_portfolio'),
    ]

    operations = [
        migrations.CreateModel(
            name='Achievement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quest_title', models.CharField(max_length=100)),
                ('quest_rank', models.CharField(max_length=10)),
                ('hunter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='achievements', to='tnk_quest.hunters')),
            ],
        ),
    ]
