# Generated by Django 4.1.12 on 2023-12-28 06:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tnk_quest', '0010_achievement'),
    ]

    operations = [
        migrations.AddField(
            model_name='quests',
            name='completed',
            field=models.BooleanField(default=False),
        ),
    ]
