# Generated by Django 4.1.12 on 2023-12-28 08:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tnk_quest', '0011_quests_completed'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quests',
            name='hunters',
            field=models.CharField(blank=True, default='', max_length=1000),
        ),
    ]
