# Generated by Django 4.1.12 on 2023-12-28 20:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tnk_quest', '0012_alter_quests_hunters'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quests',
            name='title',
            field=models.CharField(max_length=20, unique=True),
        ),
    ]
